[msg SYSTEM_GET_COSTUME_P4]
[s]Obtained the [clr 4]Yasogami Uniforms[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P3]
[s]Obtained the [clr 4]Gekkoukan Uniforms[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P2]
[s]Obtained the [clr 4]Seven Sisters[n]Uniforms[clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_IBUNR]
[s]Obtained the [clr 4]St. Hermelin[n]Uniforms[clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_IF]
[s]Obtained the [clr 4]Karukozaka[n]Uniforms[clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P4D]
[s]Obtained the [clr 4]Dancewear[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P4U]
[s]Obtained the [clr 4]Shadow Ops[n]Uniforms[clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_MEGAM]
[s]Obtained the [clr 4]Samurai Garb[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_RAIDO]
[s]Obtained the [clr 4]Student Uniforms[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_CATHE]
[s]Obtained the [clr 4]Lost Adults[n]Outfits[clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P5]
[s]Obtained the [clr 4]Regular Clothes[clr 27],[n][clr 4]School Uniforms[clr 27], and [clr 4]Loungewear[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_SWIM]
[s]Obtained the [clr 4]Swimsuits[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_BUTLE]
[s]Obtained the [clr 4]Maid and Butler Outfits[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_XMAS]
[s]Obtained the [clr 4]Christmas Outfits[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_NG]
[s]Could not receive some items[n]because you cannot hold any[n]more.[n][w][e]

[msg SYSTEM_GET_MONEY_NG]
[s]Cannot receive any more because[n]the maximum amount of money[n]is being held.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE]
[s]Obtained the Orpheus DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_2]
[s]Failed to receive the Orpheus DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA]
[s]Obtained the Izanagi DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_2]
[s]Failed to receive the Izanagi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA]
[s]Obtained the Thanatos DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA_2]
[s]Failed to receive the Thanatos DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT]
[s]Obtained the Magatsu-Izanagi[n]DLC, [clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT_2]
[s]Failed to receive the[n]Magatsu-Izanagi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY]
[s]Obtained the Kaguya DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY_2]
[s]Failed to receive the Kaguya DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD]
[s]Obtained the Ariadne DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD_2]
[s]Failed to receive the Ariadne DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER]
[s]Obtained the Asterius DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER_2]
[s]Failed to receive the Asterius DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY]
[s]Obtained the Tsukiyomi DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY_2]
[s]Failed to receive the Tsukiyomi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI]
[s]Obtained the Messiah DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI_2]
[s]Failed to receive the Messiah DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_START01]
[s]Obtained the [clr 3]healing item set[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_START01_]
[s]Failed to receive the[n][clr 3]healing item set[clr 27] DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_START02]
[s]Obtained the [clr 3]skill card set[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_START02_]
[s]Failed to receive the[n][clr 3]skill card set[clr 27] DLC.[n][w][e]

[msg SYSTEM_GET_COSTUME_P5_DA]
[s]Obtained the [clr 4]Starlight outfit[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_VELVE]
[s]Obtained the [clr 4]ultramarine outfit[n][clr 27] and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_FEATG]
[s]Obtained [clr 4]feather mask[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_DEEPS]
[s]Obtained [clr 4]Demonica with helmet[clr 27][n]and [clr 4]Demonica without helmet[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_JERSE]
[s]Obtained [clr 4]Rebellious Tracksuit[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_PQ2]
[s]Obtained the [clr 4]New Cinema wear[clr 27][n]and [clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE]
[s][clr 4] >[var 0][clr 27],[n][clr 4] >[var 1][clr 27],[n][clr 4] >[var 2][clr 27], and[n][w][e]
[s][clr 4] >[var 3][clr 27],[n][clr 4] >[var 4][clr 27],[n][clr 4] >[var 5][clr 27], and[n][w][e]
[s][clr 4][var 6][clr 27] and[n][clr 4][var 7][clr 27] obtained.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_2]
[s][clr 4] >[var 0][clr 27],[n][clr 4] >[var 1][clr 27],[n][clr 4] >[var 2][clr 27], and[n][w][e]
[s][clr 4] >[var 3][clr 27],[n][clr 4] >[var 4][clr 27],[n][clr 4] >[var 5][clr 27], and[n][w][e]
[s][clr 4] >[var 6][clr 27],[n][clr 4] >[var 7][clr 27], and[n][clr 4] >[var 8][clr 27], obtained.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_3]
[s][clr 4] >[var 0][clr 27],[n][clr 4] >[var 1][clr 27],[n][clr 4] >[var 2][clr 27], and[n][w][e]
[s][clr 4] >[var 3][clr 27],[n][clr 4] >[var 4][clr 27],[n][clr 4] >[var 5][clr 27], and[n][w][e]
[s][clr 4][var 6][clr 27] and[n][clr 4][var 7][clr 27] obtained.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_4]
[s][clr 4] >[var 0][clr 27],[n][clr 4] >[var 1][clr 27],[n][clr 4] >[var 2][clr 27], and[n][w][e]
[s][clr 4] >[var 3][clr 27],[n][clr 4] >[var 4][clr 27],[n][clr 4] >[var 5][clr 27], and[n][w][e]
[s][clr 4] >[var 6][clr 27],[n][clr 4] >[var 7][clr 27],[n][clr 4] >[var 8][clr 27], and[n][w][e]
[s][clr 4][var 9][clr 27], and[n][clr 4][var 10][clr 27] obtained.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_3]
[s]Obtained Izanagi-no-Okami[n]DLC,[clr 4][var 0][clr 27],[n]and [clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_4]
[s]Failed to receive the[n]Izanagi-no-Okami DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_3]
[s]Obtained the Orpheus DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_4]
[s]Failed to receive the Orpheus DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ATENA]
[s]Obtained the Athena DLC,[n][clr 4][var 0][clr 27], and[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ATENA_2]
[s]Failed to receive the Athena DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_RAULU]
[s]Obtained Raoul DLC[n][clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_RAULU_2]
[s]Failed to receive the Raoul DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON_]
[s]Obtained [clr 3]Exploration Assistance[n]Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON__2]
[s]Failed to receive the[n][clr 3]Exploration Assistance Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON__3]
[s]Cannot receive any more because[n]the maximum amount of money[n]is being held.[n][w][e]

[msg SYSTEM_GET_ITEM_BATTLE_P]
[s]Obtained the [clr 3]Battle Assist Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_BATTLE_P_2]
[s]Obtained the [clr 3]Battle Assist Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_P5_SAVEDATA]
[s]Received [clr 3]Persona 5 Save Data[n]special gift[clr 27].[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA]
[s]If you have Persona 5[n]Save Data, you can[n]receive various benefits.[n][w][e]
[s]Use the benefits?[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_2]
[s]Unable to acquire Save Data.[n]Would you like to try again?[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_3]
[s]You can access the Save Data[n]benefits at any time by accessing[n]the cardboard box in your room.[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_4]
[s]Obtained 〇〇.[n][w][e]

[sel SYSTEM_CHECK_P5_SAVEDATA_5 top]
[s]Yes[e]
[s]No[e]

[msg SYSTEM_DLC_GET_TOP]
[s]Received [clr 3]DLC[clr 27].[n][w][e]

[msg SYSTEM_DLC_GET_TOP_Fiber]
[s]You received your [clr 3]bonus content[clr 27].[n][w][e]

[msg MIND_MYPALACE_COMPLETE]
[s]Something is in the cardboard box...[n][w][e]
[s]Seems like a cheat item.[n][w][e]
[s]An item that'll make me undetectable to shadows...[n]Do I want this?[n][w][e]

[msg SYSTEM_MYPALACE_COMPLETE]
[s]Received [clr 3]Award Completion[n]Reward[clr 27].[n][w][e]

[msg SYSTEM_GET_GENERAL_UPPER]
[s]You cannot hold any more[n][clr 3][var 0][clr 27]. The item[n]could not be received.[n][w][e]

[msg SYSTEM_GET_GENERAL_UPPER_2]
[s]You cannot hold any more[n][clr 4][var 0][clr 27]. The item[n]could not be received.[n][w][e]

[msg SYSTEM_GET_ITEM_UPPER_LI]
[s]You cannot hold any more[n][clr 3][var 0][clr 27]. The item[n]could not be received.[n][w][e]

[sel MIND_MYPALACE_CHKONE top]
[s]Yes[e]
[s]No[e]

[msg MIND_MYPALACE_ALREADY]
[s]I already have this...[n]I'll take something else.[n][w][e]

[msg MIND_MYPALACE_COMPLETETW]
[s]Something is in the cardboard box...[n][w][e]
[s]Seems like a cheat item.[n][w][e]
[s]An item that'll make compendium summons free...[n]Do I want this?[n][w][e]

[msg MIND_DLC_OUTFITONE]
[s]Something is in the cardboard box...[n][w][e]
[s]Seems like they're purely cosmetic items.[n][w][e]

[msg SYSTEM_DLC_OUTFITS]
[s]The outfit DLC is [clr 2]purely cosmetic[clr 27] and will not[n]impact gameplay in any way.[n][w][e]

[msg MIND_DLC_OUTFITTWO]
[s]A bunch of outfits from ATLUS...[n]Do I want this?[n][w][e]

[msg MIND_DLC_ACCESSORIESONE]
[s]Something is in the cardboard box...[n][w][e]
[s]Seems like these will make my journey easier.[n]Perhaps a little too easy, even?[w][e]

[msg SYSTEM_DLC_ACCESSORY]
[s]The accessory DLC is [clr 2]extremely powerful[clr 27] and can[n]negatively impact gameplay by making it easy.[n][w][e]

[msg MIND_DLC_ACCESSORIESTWO]
[s]A bunch of accessories with powerful effects...[n]Do I want this?[n][w][e]

[msg MIND_DLC_ITEMSONE]
[s]Something is in the cardboard box...[n][w][e]
[s]Seems like these will make my journey easier.[n]Perhaps a little too easy, even?[w][e]

[msg SYSTEM_DLC_ITEMS]
[s]These items are [clr 2]quite powerful[clr 27] in the early game.[n]If you choose not to take the items, you can obtain[n]them later through normal gameplay.[n][w][e]

[msg MIND_DLC_ITEMSTWO]
[s]A bunch of miscellaneous items...[n]Do I want this?[n][w][e]

[msg MIND_DLC_MONEYONE]
[s]Something is in the cardboard box...[n][w][e]
[s]Whoa...! That's a lot of money.[n][w][e]

[msg SYSTEM_DLC_MONEY]
[s]The money DLC is [clr 2]extremely powerful[clr 27] and can[n]negatively impact gameplay by making it easy.[n][w][e]

[msg MIND_DLC_MONEYTWO]
[s]100,000 yen... Can I even spend this much?[n]Do I really want this?[n][w][e]

[msg MIND_DLC_NAOVANISH]
[s]...![n][w][e]
[s]The items I didn't take vanished![n][w][e]

[msg MIND_DUMMY]
[s]dummy[n][w][e]

