[sel YesNo]
[s]Yes[e]
[s]No[e]

[msg TestRework]
[s]DLC Rework + NG+ Arcana Bonus <3[n][w][e]

[msg TestStandalone]
[s]NG+ Arcana Bonus all alone :([n][w][e]

[msg ItemsInBox]
[s]Some things are in the box...[n][w][e]

[msg GetAkechiItem]
[s]It's a [clr 1][var 0][clr 27] worn by Akechi.[n]It shows my strong bond with him.[n]Do I want this?[n][w][e]

[msg GetSumiItem]
[s]It's a [clr 1][var 0][clr 27] used by Yoshizawa.[n]It shows my strong bond with her.[n]Do I want this?[n][w][e]

[msg GetMarukiItem]
[s]It's a [clr 1][var 0][clr 27].[n]It shows my strong bond with Maruki.[n]Do I want this?[n][w][e]

[msg LeftItemsRemoved]
[s]...![n][w][e]
[s]The items I didn't take vanished![n][w][e]
